import sqlite3
from flask import Flask, render_template
from html_helper import Table


def get_db_connection():
    conn = sqlite3.connect('database.db')
    conn.row_factory = sqlite3.Row
    return conn


app = Flask(__name__)


@app.route('/index')
def index():  # put application's code here
    conn = get_db_connection()
    posts = conn.execute('SELECT * FROM posts').fetchall()
    # Taking the posts and passing it through my Table object
    data = Table(len(posts), len(posts[0]), 5, False, posts).get_table()
    conn.close()
    # passing the list generated by my table object to the template
    return render_template('index.html', posts=data)


if __name__ == '__main__':
    app.run(debug=True)
